<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>R Training | Day 1</title>

<script src="01-Day1_junk_data_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="01-Day1_junk_data_files/bootstrap-3.3.5/css/readable.min.css" rel="stylesheet" />
<script src="01-Day1_junk_data_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="01-Day1_junk_data_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="01-Day1_junk_data_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="01-Day1_junk_data_files/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="01-Day1_junk_data_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="01-Day1_junk_data_files/tocify-1.9.1/jquery.tocify.js"></script>
<script src="01-Day1_junk_data_files/navigation-1.1/tabsets.js"></script>
<link href="01-Day1_junk_data_files/font-awesome-5.0.13/css/fa-svg-with-js.css" rel="stylesheet" />
<script src="01-Day1_junk_data_files/font-awesome-5.0.13/js/fontawesome-all.min.js"></script>
<script src="01-Day1_junk_data_files/font-awesome-5.0.13/js/fa-v4-shims.min.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="css\camp_style.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">



<h1 class="title toc-ignore">R Training | Day 1</h1>

</div>


<div id="welcome-to-r-camp" class="section level1 unnumbered">
<h1>Welcome to R Camp</h1>
<hr>
<div class="figure">
<img src="images/day1_bb8_sq.png" style="float: left; margin-right: 60px; margin-top: -10px;" width="260" />

</div>
<p><br><br><br><br><br></p>
<div id="please-power-on-your-droid" class="section level3 unnumbered">
<h3>Please power on your droid</h3>
<p><a href="https://github.com/MPCA-air/RTrain/blob/master/data/starwars_scrap_jakku.zip?raw=true"> <span class="btn_code_blue"> <strong>DOWNLOAD</strong> </span></a> — Day 1 data files</p>
<p><br><br><br><br></p>
</div>
</div>
<div id="a-new-day" class="section level1">
<h1><span class="header-section-number">1</span> | A new day</h1>
<hr>
<p>Welcome to Jakku! You’ve just in time. The Junk boss Unkar is being an awful meany-pants and has started skimping on rations. And Rey needs some parts to build a star ship to escape Jakku and fight with the New Republic. Luckily for us, BB8 was able snag a transfer log from Unkar’s droid showing all of his recent shipments. Let’s power on our Datapad and see if we can’t make some trouble for Unkar and track down the parts we need.</p>
<p><br></p>
<p><strong>Start a new project</strong></p>
<ul>
<li>In <em>Rstudio</em> select <em>File</em> from the top menu bar</li>
<li>Choose <em>New Project…</em> &gt; <em>New Directory</em> &gt; <em>New Project</em></li>
<li>Enter a project name such as <code>&quot;junk data&quot;</code></li>
<li>Select <em>Browse…</em> and choose a folder where you store your data work</li>
<li>Ignore the rest and jump down to click <em>Create Project</em></li>
</ul>
<p><strong>Get the data</strong></p>
<ul>
<li>Create a new <code>data</code> folder in your project folder</li>
<li>Move the data you downloaded above to it</li>
</ul>
<div id="r-scripts" class="section level2">
<h2><span class="header-section-number">1.1</span> R scripts</h2>
<p>An R <em>script</em> is where you write R code and document your work. They’re like recipes or prescriptions that tell the computer what you want to happen to your data.</p>
<p><strong>Open a new R script</strong></p>
<ul>
<li>In the upper left, click on the white file icon with the green (+) sign.</li>
<li>Select <em>R Script</em>.</li>
</ul>
<div class="figure">
<img src="http://docplayer.net/docs-images/25/5462802/images/10-0.png" width="450" />

</div>
<p><br></p>
<p><strong>Save script</strong></p>
<ul>
<li>Click on the floppy disk icon</li>
<li>Enter a file name such as <code>starwars_code.R</code></li>
</ul>
</div>
<div id="a-tour-of-rstudio" class="section level2">
<h2><span class="header-section-number">1.2</span> A tour of RStudio</h2>
<p><img src="http://www.sthda.com/sthda/RDoc/images/rstudio.png" width="580"></p>
<p><br></p>
<p><strong>1. Code editor</strong></p>
<p>This is where you can edit your R scripts. The tabs at the top of the code editor allow you to view scripts and data sets you have open. You can press <strong>CTRL+ENTER</strong> to run a block of code in your R script. We’ll spend most of our time here. It’s the homebase in RStudio.</p>
<p><strong>2. Console</strong></p>
<p>This is where code is executed by the computer. It shows code that you have run and any errors, warnings, or other messages that result. You can input code directly into the console and run it, but it won’t be saved for later. That’s why we like to run all of our code directly from a script in the code editor above.</p>
<p><strong>3. Workspace</strong></p>
<p>This pane shows all of the objects and functions that you’ve created, as well as a history of the code you’ve run during your current session. The environment tab shows all of the data, objects and functions that you’ve loaded. Note the <em>broom</em> icon below the Connections tab. This cleans shop and allows you to clear out all of the objects in your work space.</p>
<p><strong>4. Plots and files</strong></p>
<p>These tabs allow you to view and open files in your current directory, view plots and other visual objects like maps, view installed packages, and access the Help window. If at anytime you’re unsure what a function or package does, enter it’s name after a question mark in the console. For example, try typing <code>?mean</code> in the console and then pressing <strong>ENTER</strong>.</p>
</div>
<div id="help" class="section level2 unnumbered">
<h2>Help!</h2>
<hr>
<p><strong>Learn more R</strong></p>
<ul>
<li>In your browser: <a href="https://campus.datacamp.com/courses/free-introduction-to-r/chapter-1-intro-to-basics-1?ex=1">DataCamp Intro</a></li>
<li>RStudio lessons: <a href="https://rstudio.github.io/learnr/examples.html" class="uri">https://rstudio.github.io/learnr/examples.html</a></li>
<li>RStudio videos: <a href="https://tutorials.shinyapps.io/04-Programming-Basics/#section-welcome" class="uri">https://tutorials.shinyapps.io/04-Programming-Basics/#section-welcome</a></li>
<li>Learn inside R: <a href="https://swirlstats.com/students.html">swirlR</a><br />
</li>
<li>Coursera classes: <a href="https://www.coursera.org/specializations/jhu-data-science">John Hopkins courses w/ Roger Peng</a></li>
</ul>
<p><strong>Books</strong></p>
<ul>
<li><a href="http://r4ds.had.co.nz/"><strong>R for Data Science</strong></a>: comprehensive &amp; free book online</li>
<li>R Cookbook: <a href="https://www.cookbook-r.com" class="uri">https://www.cookbook-r.com</a></li>
</ul>
<p><strong>Searching online</strong></p>
<ul>
<li><a href="www.google.com">google.com</a>: include <code>r</code> or <code>rstats</code> + <code>the question</code></li>
<li><a href="https://stackoverflow.com/questions/12675147/how-can-we-make-xkcd-style-graphs">stackoverflow.com</a> + use the <code>[r]</code> tag</li>
</ul>
<p><strong>R community</strong></p>
<ul>
<li>R Bloggers: <a href="https://www.r-bloggers.com/" class="uri">https://www.r-bloggers.com/</a></li>
<li><code>#rstats</code> on Twitter</li>
<li>R Ladies: <a href="https://rladies.org/" class="uri">https://rladies.org/</a></li>
</ul>
<p><br></p>
</div>
<div id="you-are-not-alone-in-this-universe" class="section level2 unnumbered">
<h2>You are not alone in this universe</h2>
<p>Growth of R Ladies groups</p>
<div class="figure">
<img src="images/rladies_map.gif" />

</div>
<p><br></p>
</div>
<div id="make-it-like-home" class="section level2">
<h2><span class="header-section-number">1.3</span> Make it like home</h2>
<div class="figure">
<img src="images/font_change.png" style="margin-left: 20px; float: right;" width="410" />

</div>
<p>Let’s add some of our own style so we feel more at home. Follow these steps to change the font-size and color scheme:</p>
<ol style="list-style-type: decimal">
<li>Go to <strong>Tools</strong> on the top navigation bar.</li>
<li>Choose <code>Global Options...</code></li>
<li>Choose <code>Appearance</code> with the paint bucket.</li>
<li>Find something you like.</li>
<li>Try ‘solarized dark’ when you’re ready to embrace winter.</li>
<li>The default font and theme are ‘Lucida Console’ and ‘TextMate’.</li>
</ol>
<p><br><br><br><br><br></p>
</div>
</div>
<div id="first-steps" class="section level1">
<h1><span class="header-section-number">2</span> | First steps</h1>
<hr>
<p>You can assign values to new objects using the “left arrow” <code>&lt;-</code>, more officially known as the <em>assignment operator</em>. Try adding the code below to your R script and creating an object called <code>droid</code>.</p>
<p>To run a line of code in your script, move the cursor to that line and press <strong>CTRL+ENTER</strong>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Create a new object</span>
droid &lt;-<span class="st"> &quot;bb8&quot;</span>

droid 

wookie &lt;-<span class="st"> &quot;Chewbacca&quot;</span>

wookie


<span class="co"># To save text to a character object you need quotation marks: &quot;text&quot;</span>
<span class="co"># Try this:</span>
wookie &lt;-<span class="st"> </span>Chewbacca


<span class="co"># Without quotes, R looks for an object called Chewbacca, and then lets you know that it couldn’t find one. </span></code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># To copy an object save it to a new name.</span>
wookie2 &lt;-<span class="st"> </span>wookie


<span class="co"># Or overwrite an object</span>
wookie &lt;-<span class="st"> &quot;Tarfful&quot;</span>
  
wookie


<span class="co"># Did this change the value stored in wookie2?</span>
wookie2  </code></pre></div>
<p><br></p>
<div id="drop-and-remove-data" class="section level3 unnumbered">
<h3>Drop and remove data</h3>
<p>You can drop objects with the remove function <code>rm()</code>. Try it out on some of your wookies.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Delete objects to clean-up your environment</span>
<span class="kw">rm</span>(wookie)

<span class="kw">rm</span>(wookie2)


<span class="co"># How can we get the &#39;wookie&#39; object back?</span>
<span class="co"># Hint: The UP arrow is your friend.</span></code></pre></div>
<p><br></p>
<details> <summary class = "btn_code_green"> <strong>GOOD NEWS: </strong> Deleting data is okay </summary>
<p>
<div class="tip">
<p>Don’t worry about deleting data or objects, you can always recreate them! And when R loads data files it only copies the contents. All your original data files remain safe and won’t suffer from any accidental changes. If something disappears or goes wrong in R, it’s okay. You can always reload the data using your script.</p>
</div>
</p>
<p></details></p>
</div>
<div id="give-it-a-name" class="section level2">
<h2><span class="header-section-number">2.1</span> Give it a name</h2>
<p>Everything has a name in R and you can name things almost anything you like. You can even name your data <code>TOP_SECRET_shhhhhh...</code> or <code>Luke_I_am_your_father</code> or <code>data_McData_face</code>.</p>
<p>Sadly, there are a <em>few</em> minor restrictions. Names cannot include spaces or special characters that might be found in math equations, like <code>+</code>, <code>-</code>, <code>*</code>, <code>\</code>, <code>/</code>, <code>=</code>, <code>!</code>, or <code>)</code>.</p>
<div id="exercise" class="section level3 unnumbered">
<h3><i class="fa fa-astronaut" aria-hidden="true" style="color: green"></i> Exercise!</h3>
<p>Try running some of these examples in your R console. Find new ways to create errors. The more broken the more better!</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n wookies &lt;-<span class="st"> </span><span class="dv">5</span>

n<span class="op">*</span>wookies &lt;-<span class="st"> </span><span class="dv">5</span>

n_wookies &lt;-<span class="st"> </span><span class="dv">5</span>

n.wookies &lt;-<span class="st"> </span><span class="dv">5</span>


all_the_wookies<span class="op">!</span><span class="st"> </span><span class="er">&lt;</span><span class="op">-</span><span class="st"> &quot;Everyone on Kashyyyk&quot;</span></code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># You can add one wookie</span>
n_wookies &lt;-<span class="st"> </span>n_wookies <span class="op">+</span><span class="st"> </span><span class="dv">1</span>


<span class="co"># But what if you have 10,000 wookies?</span>
n_wookies &lt;-<span class="st"> </span><span class="dv">10</span>,<span class="dv">000</span>


<span class="co"># They also cannot begin with a number.</span>
1st_wookie &lt;-<span class="st"> &quot;Chewbacca&quot;</span>

88b &lt;-<span class="st"> &quot;droid&quot;</span>

<span class="co"># But they can contain numbers!</span>
wookie1    &lt;-<span class="st"> &quot;Chewbacca&quot;</span>

bb8 &lt;-<span class="st"> &quot;droid&quot;</span></code></pre></div>
<p><br></p>
<details> <summary class = "btn_code_blue"> <strong>EXPLORE:</strong> What happens when we create <strong>n_wookies</strong> the second time? </summary>
<p>
<blockquote>
<p>When we create a new object that has the same name as something that already exists, the new object replaces the old one. Sometimes we’ll want to update an existing object and replace the old version. Other times we may want to copy an object to a new name to preserve the original. This is similar to choosing between <em>Save</em> and <em>Save As</em> when we save a file.</p>
</blockquote>
</p>
<p></details></p>
</div>
</div>
<div id="multiple-items" class="section level2">
<h2><span class="header-section-number">2.2</span> Multiple items</h2>
<p>We can add multiple values inside <code>c()</code> to make a vector of items. It’s like a chain of items, where each additional item is connected by a comma. The <code>c</code> stands for to concatenate or to combine values into a vector.</p>
<p>Let’s use <code>c()</code> to create a few vectors of names.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Create a character vector and name it starwars_names</span>
starwars_names &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Luke&quot;</span>, <span class="st">&quot;Leia&quot;</span>, <span class="st">&quot;Han Solo&quot;</span>)

<span class="co"># Print starwars_names to the console</span>
starwars_names</code></pre></div>
<pre><code>## [1] &quot;Luke&quot;     &quot;Leia&quot;     &quot;Han Solo&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Create a numeric vector and name it starwars_ages</span>
starwars_ages  &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">19</span>,<span class="dv">18</span>,<span class="dv">25</span>)

<span class="co"># Print the ages to the console</span>
starwars_ages</code></pre></div>
<pre><code>## [1] 19 18 25</code></pre>
</div>
<div id="make-a-table" class="section level2">
<h2><span class="header-section-number">2.3</span> Make a table</h2>
<p>A table in R is known as a <strong>data frame</strong>. We can think of it as a group of columns, where each column is made from a vector. Data frames in R have columns of data that are all the same length.</p>
<div class="figure">
<img src="images/vector_to_dataframe.png" style="margin-left: 100px;" width="510" />

</div>
<p><br></p>
<p>Let’s make a data frame with two columns to hold the names and ages of our characters from above.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Create table with columns &quot;names&quot; and &quot;ages&quot; with values from the starwars_names and starwars_ages vectors</span>
starwars_df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">names =</span> starwars_names,
                          <span class="dt">ages  =</span> starwars_ages)

<span class="co"># Print the starwars_df data frame to the console</span>
starwars_df</code></pre></div>
<pre><code>##      names ages
## 1     Luke   19
## 2     Leia   18
## 3 Han Solo   25</code></pre>
<p><br></p>
<div id="exercise-1" class="section level3 unnumbered">
<h3><i class="fa fa-astronaut" aria-hidden="true" style="color: green"></i> Exercise!</h3>
<blockquote>
<p>Create the same table above with a 3rd column showing their father’s names: <code>c(&quot;Darth&quot;, &quot;Darth&quot;, &quot;Unknown&quot;)</code></p>
</blockquote>
<p><br></p>
</div>
<div id="get-values-from-a-column_name" class="section level3 unnumbered">
<h3>Get values from a <code>$column_name</code></h3>
<p>Use the <code>$</code> sign after the name of your table to see the values in one of your columns.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># View the &quot;ages&quot; column in starwars_df</span>
starwars_df<span class="op">$</span>ages</code></pre></div>
<pre><code>## [1] 19 18 25</code></pre>
<div class="quiz">
<h3 id="pop-quiz-hotshot" class="unnumbered">Pop Quiz, hotshot!</h3>
<p><strong>Which of these names are valid for a new object?</strong> <em>(Hint: You can test them.)</em></p>
<p><input type="radio"> <em>my starwars fandom</em> <br> <input type="radio"> <em>my_wookies55</em> <br> <input type="radio"> <em>5wookies</em> <br> <input type="radio"> <em>my-wookie</em> <br> <input type="radio"> <em>Wookies!!!</em> <br></p>
<p><br></p>
<details> <summary class = "btn_code"><em>Show solution</em></summary>
<p>
<p><i class="fa fa-check" aria-hidden="true" style="color: green;"></i> <code>my_wookies55</code></p>
<p><em>Yes!! The FORCE is strong with you!</em></p>
</p>
<p></details></p>
</div>
</div>
</div>
<div id="leave-a-comment" class="section level2">
<h2><span class="header-section-number">2.4</span> Leave a <code>#comment</code></h2>
<p>The text in the scripts with the <code>#</code> in front are called comments. A line that starts with a <code>#</code> is ignored and won’t be run as R code. You can use the <code>#</code> to add notes in your script to make it easier for others and yourself to understand what is happening and why. You can also use comments to add warnings or instructions for others using your code.</p>
</div>
<div id="functions" class="section level2">
<h2><span class="header-section-number">2.5</span> Functions</h2>
<p>Now that you know what objects are and how to create them, let’s learn how to use them in functions. Functions take one or more inputs called “arguments”. They perform steps based on the arguments and usually return an output object.</p>
<p><br></p>
<details> <summary class = "btn_code_blue"><em>Clone Trooper function</em></summary>
<p>
<p>You can think of a function like a plan for making Clone Troopers.</p>
<div class="figure">
<img src="images/clonetrooper_fathead.png" style="float: left; margin-right: 36px; margin-top: -2px;" width="220" />

</div>
<p><br></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">create_clones</span>(<span class="dt">host       =</span> <span class="st">&quot;Jango Fett&quot;</span>, 
              <span class="dt">n_troopers =</span> <span class="dv">2000</span>)</code></pre></div>
<p><br><br></p>
<p>The function above creates Clone Troopers based on two arguments: the <code>host</code> and <code>n_troopers</code>. When we have more than one argument, we use a comma to separate them. With some luck, the function will successfully return a new object - a group of 2,000 Clone Troopers.</p>
<p><br><br><br><br><br></p>
<hr>
</p>
<p></details></p>
<p><br></p>
<div id="the-sum-function" class="section level3 unnumbered">
<h3>The <code>sum()</code> function</h3>
<p>We already covered two functions: <code>c()</code> and <code>data.frame()</code>. Now let’s use the <code>sum()</code> function to find the sum age of our Star Wars characters.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Call the sum function with starwars_ages as input</span>
ages_sum &lt;-<span class="st"> </span><span class="kw">sum</span>(starwars_ages) <span class="co"># Assigns the output to starwars_ages_sum</span>

<span class="co"># Print the starwars_ages_sum value to the console</span>
ages_sum</code></pre></div>
<pre><code>## [1] 62</code></pre>
<p><br></p>
<p>The <code>sum()</code> function takes the <em>starwars_ages</em> vector as input, performs some calculations, and returns a single numeric object. Note that we assigned the output object to the name <code>ages_sum</code>. If we don’t assign the output object it will be printed to the console and won’t be saved. Sometimes that’s what we want, especially when we’re exploring the data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Alternative without assigning output</span>
<span class="kw">sum</span>(starwars_ages) </code></pre></div>
<pre><code>## [1] 62</code></pre>
<p><br></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">starwars_ages</code></pre></div>
<pre><code>## [1] 19 18 25</code></pre>
<blockquote>
<p><strong>NOTE:</strong> The original <code>starwars_ages</code> vector hasn’t changed. Each function has its own “environment” and its calculations happen inside a bubble. In general, what happens inside a function won’t change your objects outside of the function.</p>
</blockquote>
</div>
</div>
<div id="function-summary" class="section level2 unnumbered">
<h2>Function summary</h2>
<p>There are functions in R that are more complex but most boil down to the same general setup:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">new_output &lt;-<span class="st"> </span><span class="cf">function</span>(argument_input1, argument_input2)</code></pre></div>
<p>We call a function and then add input arguments inside the parentheses. In exchange, the function returns an output object. You can make your own functions in R and name them almost anything you like, even <code>my_amazing_starwars_function()</code>.</p>
<p><br></p>
<details> <summary class = "btn_code_blue"> <strong>EXPLORE:</strong> What <strong>arguments</strong> does my function have? </summary>
<p>
<div class="note">
<p>Functions often have more than one argument. Type <code>?read_csv</code> into your console to see help in the lower-right pane that describes all of the function’s arguments and what they do.</p>
<p>Many of the options have default arguments (such as <code>col_names = TRUE</code>) that the function uses if you don’t provide an alternative. A short scroll down in the help window will show you more details about the arguments and the values they take.</p>
<p><code>function(arg1 = input1, arg2 = input2, arg3...)</code></p>
<p>The <em>file</em> argument tells us that the function expects a path to a file. It can be given many types of files, even a <em>ZIP</em> file. Below that, you’ll see the <em>col_names</em> argument. This argument takes either <code>TRUE</code>, <code>FALSE</code>, or a character vector of column names. The default is <code>TRUE</code>, which means the first row in the CSV will be used for the column names of your table.</p>
</div>
</p>
<p></details></p>
<div class="quiz">
<h3 id="pop-quiz" class="unnumbered">Pop Quiz!</h3>
<p><strong>Which of these is a valid function call?</strong></p>
<p><input type="radio"> <em>train(“concentrate” “Force”)</em> <br> <input type="radio"> <em>shoot, “lightsaber”, “Death Ray”</em> <br> <input type="radio"> <em>replicate(100000000, “clones”)</em> <br> <input type="radio"> <em>fight(until Empire conquered)</em> <br> <input type="radio"> <em>scrap(100 Datapads, “Hyperdrives”)</em> <br></p>
<br> <details> <summary class = "btn_code"><em>Show solution</em></summary>
<p>
<p><i class="fa fa-check" aria-hidden="true" style="color: green;"></i> <code>replicate(100000000, &quot;clones&quot;)</code></p>
<p><em>Correct! You are ready to audit a Junk dealer.</em></p>
</p>
</details>
</div>
</div>
</div>
<div id="read-data" class="section level1">
<h1><span class="header-section-number">3</span> | Read data</h1>
<hr>
<p>The first step of a good scrap audit is reading/loading some data and figuring out where all the scrap is going. Here is a small dataset showing the scrap from Jakku. It was salvaged from a crash site and the transfer was incomplete.</p>
<table>
<thead>
<tr class="header">
<th align="left">source</th>
<th align="left">destination</th>
<th align="left">item</th>
<th align="right">quantity</th>
<th align="right">price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Coruscant</td>
<td align="left">Jakuu</td>
<td align="left">hyperdrives</td>
<td align="right">3</td>
<td align="right">300</td>
</tr>
<tr class="even">
<td align="left">Tatooine</td>
<td align="left">Jakuu</td>
<td align="left">datapads</td>
<td align="right">100</td>
<td align="right">25</td>
</tr>
<tr class="odd">
<td align="left">Naboo</td>
<td align="left">Jakuu</td>
<td align="left">hyperdrives</td>
<td align="right">45</td>
<td align="right">45</td>
</tr>
<tr class="even">
<td align="left">Endor</td>
<td align="left">Jakuu</td>
<td align="left">hyperdrives</td>
<td align="right">1</td>
<td align="right">10000000</td>
</tr>
</tbody>
</table>
<div id="new-message-1" class="section level2 unnumbered">
<h2>New Message <em>(1)</em></h2>
<details> <summary class = "btn_code_green"><em>Incoming…</em> <em>BB8</em></summary>
<p>
<div class="tip">
<p><strong>BB8:</strong> <em>Beep boop Beep.</em></p>
<p><strong>BB8:</strong> <em>I intercepted a large scrapper data set from droid 4 of Junk Boss Plutt.</em></p>
<p><br></p>
<p>Receiving data now…</p>
<details> <summary class = "btn_code_green"> View data </summary>
<p>
<p><strong>scrap_records.csv</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Salvage,Origin,Dest,Amount,Units,Price_per_Ton  
Flight recorder,Outskirts,Niima Outpost,<span class="dv">887</span>,Tons,<span class="fl">590.93</span>  
Proximity sensor,Outskirts,Raiders,<span class="dv">7081</span>,Tons,<span class="fl">1229.03</span>  
Aural sensor,Tuanul,Raiders,<span class="dv">707</span>,Tons,<span class="fl">145.27</span>  
Electromagnetic filter,Tuanul,Niima Outpost,<span class="dv">107</span>,Tons,<span class="fl">188.2</span>  
...  </code></pre></div>
<p><br></p>
<p><strong>You:</strong> <em>This looks like a mess! What do I do with this BB8?</em></p>
</p>
</details>
</p>
</details>
</tip>
</div>
<div id="csv-to-the-rescue" class="section level2">
<h2><span class="header-section-number">3.1</span> CSV to the rescue</h2>
<p>The main data format used in R is the <strong>CSV</strong> <em>(comma-separated values)</em>. A <strong>CSV</strong> is a simple text file that can be opened in R and most other stats software, including Excel. It looks squished together as plain text, but that’s okay! When opened in R, the text becomes a familiar looking table with columns and rows. But before we launch ahead, let’s add a <em>package</em> to R that will help us read <strong>CSV</strong> files.</p>
<p><br></p>
<details><summary class = "btn_code_blue"> How to save a CSV from Excel </summary>
<p>
<p><strong>Step 1:</strong> Open your Excel file.</p>
<p><strong>Step 2:</strong></p>
<ul>
<li>Go to <em>File</em><br />
</li>
<li><em>Save As</em><br />
</li>
<li><em>Browse</em> to your project folder<br />
</li>
<li>Save as type: _CSV (Comma Delimited) (*.csv)_
<ul>
<li>Any of the <em>CSV</em> options will work<br />
</li>
</ul></li>
<li>Click <strong>Yes</strong><br />
</li>
<li>Close Excel (Click “Don’t Save” as much as you need to. Seriously, we just saved it. Why won’t Excel just leave us alone?)</li>
</ul>
<p>Return to RStudio and open your project. Look at your <em>Files</em> tab in the lower right window. Click on the <em>CSV</em> file you saved and choose <strong>View File</strong>. Success!</p>
<p><br></p>
<hr>
</p>
<p></details></p>
</div>
</div>
<div id="a-new-package" class="section level1">
<h1><span class="header-section-number">4</span> | A new package 📦</h1>
<hr>
<p>A <em>package</em> is a small add-on for R like a phone App for your phone. Packages add capabilities like statistical functions, mapping powers, and special charts. In order to use a new package we first need to install it.</p>
<div id="readr" class="section level2">
<h2><span class="header-section-number">4.1</span> <em>readr</em></h2>
<hr>
<div class="figure">
<img src="https://d21ii91i3y6o6h.cloudfront.net/gallery_images/from_proof/9289/medium/1447092171/readr-hexbin-sticker-from-rstudio.png" align="left" style="margin-right:18px;" width="145" />

</div>
<p><br></p>
<p>The <em>readr</em> package helps import data into R in different formats. It does extra work for you like cleaning the data of extra white space and formatting tricky dates. Your packages are stored in your R <em>library</em>.</p>
<p><br><br></p>
<p><strong>Add a package to your library</strong></p>
<ol style="list-style-type: decimal">
<li>Open <em>RStudio</em></li>
<li>Type <code>install.packages(&quot;readr&quot;)</code> in the lower left console</li>
<li>Press Enter</li>
<li><em>Wait two seconds</em></li>
<li>Open the <code>Packages</code> tab in the lower right window of RStudio to see the packages in your <em>library</em>
<ul>
<li>Use the search bar to find the <code>readr</code> package</li>
</ul></li>
</ol>
<p><br></p>
<p>The packages tab only shows the available packages that are installed. To use one of them, you will need to load it. Loading a package is like opening an App on your phone. To load a package we need to use the <code>library()</code> function. After loading the <em>readr</em> package you can read the Jakku scrap data with the brand new function <code>read_csv()</code>.</p>
<p><br></p>
</div>
<div id="read-the-data" class="section level2">
<h2><span class="header-section-number">4.2</span> Read the data</h2>
<hr>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;readr&quot;</span>)

<span class="kw">read_csv</span>(<span class="st">&quot;data/starwars_scrap_jakku.csv&quot;</span>)</code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   Salvage = col_character(),
##   Origin = col_character(),
##   Dest = col_character(),
##   Amount = col_integer(),
##   Units = col_character(),
##   Price_per_Ton = col_double()
## )</code></pre>
<pre><code>## # A tibble: 222 x 6
##    Salvage                  Origin   Dest       Amount Units Price_per_Ton
##    &lt;chr&gt;                    &lt;chr&gt;    &lt;chr&gt;       &lt;int&gt; &lt;chr&gt;         &lt;dbl&gt;
##  1 Flight recorder          Outskir~ Niima Out~    887 Tons           591.
##  2 Proximity sensor         Outskir~ Raiders      7081 Tons          1229.
##  3 Vitus-Series Attitude T~ Reestki  Raiders      4901 Tons           226.
##  4 Aural sensor             Tuanul   Raiders       707 Tons           145.
##  5 Electromagnetic dischar~ Tuanul   Niima Out~    107 Tons           188.
##  6 Proximity sensor         Tuanul   Trade car~  32109 Tons          1229.
##  7 Hyperdrive motivator     Tuanul   Trade car~    862 Tons          1485.
##  8 Landing jet              Reestki  Niima Out~  13944 Tons          1497.
##  9 Electromagnetic dischar~ Cratert~ Raiders      7788 Tons           188.
## 10 Sublight engine          Outskir~ Niima Out~  10642 Tons          7211.
## # ... with 212 more rows</code></pre>
<p><br></p>
<p><strong>NOTE:</strong> When your project is open, RStudio sets the working directory to your project folder. When reading in files or data from a folder outside of your project, you will need to use the full file path location. For example: <code>X://Programs/Air_Quality_Programs/Traffic_data.csv</code></p>
</div>
<div id="name-that-data-frame" class="section level2 unnumbered">
<h2>Name that Data Frame</h2>
<p>Where did the data go after you read it into R? If we want to work with the data in R, we need to give it a name with the assignment operator: <code>&lt;-</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Read in scrap data and set name to &quot;scrap&quot;</span>
scrap &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/starwars_scrap_jakku.csv&quot;</span>)

<span class="co"># Type the name of the table to view it in the console</span>
scrap</code></pre></div>
<pre><code>## # A tibble: 222 x 6
##    Salvage                  Origin   Dest       Amount Units Price_per_Ton
##    &lt;chr&gt;                    &lt;chr&gt;    &lt;chr&gt;       &lt;int&gt; &lt;chr&gt;         &lt;dbl&gt;
##  1 Flight recorder          Outskir~ Niima Out~    887 Tons           591.
##  2 Proximity sensor         Outskir~ Raiders      7081 Tons          1229.
##  3 Vitus-Series Attitude T~ Reestki  Raiders      4901 Tons           226.
##  4 Aural sensor             Tuanul   Raiders       707 Tons           145.
##  5 Electromagnetic dischar~ Tuanul   Niima Out~    107 Tons           188.
##  6 Proximity sensor         Tuanul   Trade car~  32109 Tons          1229.
##  7 Hyperdrive motivator     Tuanul   Trade car~    862 Tons          1485.
##  8 Landing jet              Reestki  Niima Out~  13944 Tons          1497.
##  9 Electromagnetic dischar~ Cratert~ Raiders      7788 Tons           188.
## 10 Sublight engine          Outskir~ Niima Out~  10642 Tons          7211.
## # ... with 212 more rows</code></pre>
<p><br></p>
<div id="pro-tip" class="section level3 unnumbered">
<h3><i class="fas fa-user-astronaut" aria-hidden="true" style="color:#040707;"></i> Pro-tip!</h3>
<p>Did you notice the row of <three> letter abbreviations under the column names? These describe the data type of each column.</p>
<blockquote>
<p><code>chr</code> stands for <strong>character</strong> vector, or a string of characters. Examples: <em>“apple”</em>, <em>“apple5”</em>, <em>“5 red apples”</em><br />
<code>int</code> stands for <strong>integer</strong>. Examples: <em>5</em>, <em>34</em>, <em>1071</em><br />
<code>dbl</code> stands for <strong>double</strong>. Examples: <em>5.0000</em>, <em>3.4E-6</em>, <em>10.7106</em></p>
</blockquote>
<p>We will discover more data types later on, such as <code>dates</code> and <code>logical</code> (TRUE/FALSE).</p>
<div class="quiz">
<h3 id="pop-quiz-1" class="unnumbered">Pop Quiz!</h3>
<p><strong>What data type is the <code>Dest</code> column?</strong></p>
<p><input type="radio"> <em>letters</em> <br> <input type="radio"> <em>character</em> <br> <input type="radio"> <em>words</em> <br> <input type="radio"> <em>numbers</em> <br> <input type="radio"> <em>integer</em> <br></p>
<p><br></p>
<details> <summary class = "btn_code"><em>Show solution</em></summary>
<p>
<p><i class="fa fa-check" aria-hidden="true" style="color: green;"></i> <code>character</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#  </span></code></pre></div>
</p>
</summary>
</div>
<p><br></p>
</div>
<div id="dont-like-the-column-names" class="section level3 unnumbered">
<h3>Don’t like the column names?</h3>
<p>We can give new column names to the <em>col_names</em> argument in <code>read_csv()</code> like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Assign desired column names as a character vector named my_header_names</span>
my_header_names &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;scrap_type&quot;</span>, <span class="st">&quot;source&quot;</span>, <span class="st">&quot;destination&quot;</span>, <span class="st">&quot;count&quot;</span>, <span class="st">&quot;units&quot;</span>, <span class="st">&quot;price_per_ton&quot;</span>)

scrap &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/starwars_scrap_jakku.csv&quot;</span>, <span class="dt">col_names =</span> my_header_names)</code></pre></div>
</div>
<div id="skip-a-row" class="section level3 unnumbered">
<h3>Skip a row</h3>
<p>We now have the column names we want, but the original column names in our CSV file show up as a row in our data. We want <code>read_csv</code> to ignore the first row. Let’s look through the help window and try to find an argument that can help us. The <code>skip</code> argument looks like it could be helpful. Sure enough, the description is exactly what we’re looking for here. The default is <code>skip = 0</code> (read every line), but we can skip the first line by providing <code>skip = 1</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">my_header_names &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;scrap_type&quot;</span>, <span class="st">&quot;source&quot;</span>, <span class="st">&quot;destination&quot;</span>, <span class="st">&quot;count&quot;</span>, <span class="st">&quot;units&quot;</span>, <span class="st">&quot;price_per_ton&quot;</span>)

<span class="kw">read_csv</span>(<span class="st">&quot;data/starwars_scrap_jakku.csv&quot;</span>, my_header_names, <span class="dt">skip =</span> <span class="dv">1</span>)</code></pre></div>
<p><br></p>
<details> <summary class = "btn_code_blue"> <strong>EXPLORE:</strong> Does the order of arguments matter? </summary>
<p>
<p>You may be wondering why we included <code>skip =</code> for the skip argument, but only provided the objects for the other two arguments. When you pass inputs to a function, R assumes you’ve entered them in the same order that is shown on the ?help page. Let’s say you had a function called <code>feed_creatures()</code> with 3 arguments:</p>
<blockquote>
<p><code>feed_creatures(porg = &quot;small fish&quot;, ewok = &quot;vegetables&quot;, tauntaun = &quot;lichen&quot;)</code>.</p>
</blockquote>
<p>A shorthand way to write this would be <code>feed_creatures(&quot;small fish&quot;, &quot;vegetables&quot;, &quot;lichen&quot;)</code>. This works becuase all the arguments remain in the default order.</p>
<p>However, if we write <code>feed_creatures(&quot;vegetables&quot;, &quot;lichen&quot;, &quot;small fish&quot;)</code>, the function will send <em>vegetables</em> to the porgs and <em>lichen</em> to the Ewoks. That’s no good. If we really want to write “lichen” second, we need to tell R which food item belongs to each animal, such as <code>feed_creatures(&quot;small fish&quot;, tauntaun = &quot;lichen&quot;, ewok = &quot;vegetables&quot;)</code>.</p>
<p>The same thing goes for <code>read_csv()</code>. In <code>read_csv(scrap_file, column_names, skip = 1)</code>, R assumes the file is <code>scrap_file</code> and that the col_names should be set to <code>column_names</code>. The <code>skip =</code> argument has to be included explicitly because <em>skip</em> is the <strong>10th</strong> argument in <code>read_csv()</code>. If we don’t include <code>skip =</code>, R will assume the value we entered is meant for the function’s <strong>3rd</strong> argument.</p>
</p>
<p></details></p>
<p><br></p>
</div>
<div id="pro-tip-1" class="section level3 unnumbered">
<h3><i class="fas fa-user-astronaut" aria-hidden="true" style="color:#040707;"></i> Pro-tip!</h3>
<p>A shortcut to see all possible function arguments is to enter its name in the console followed by the first parenthesis, such as <code>read_csv(</code>. Now press <code>TAB</code> on the keyboard. This will bring up a drop-down menu of all the available arguments for that function.</p>
</div>
</div>
<div id="saving-file-paths" class="section level2">
<h2><span class="header-section-number">4.3</span> Saving file paths</h2>
<hr>
<p>You can also save file paths as objects, such as <code>file_path &lt;- &quot;data/starwars_scrap_jakku.csv&quot;</code>. Now you can use it as a shortcut to the location of your data. When you want to load the scrap table you can write <code>read_csv(file_path)</code>. This handy trick makes it easier for you or your coworker to update your code and use it with new data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Save the file path to an object you can use later</span>
file_path &lt;-<span class="st"> &quot;data/starwars_scrap_jakku.csv&quot;</span>

scrap &lt;-<span class="st"> </span><span class="kw">read_csv</span>(file_path)</code></pre></div>
<div class="quiz">
<h3 id="pop-quiz-2" class="unnumbered">Pop Quiz!</h3>
<p><br></p>
<p><strong>What package does <code>read_csv()</code> come from?</strong></p>
<p><input type="radio"> <em>dinosaur</em> <br> <input type="radio"> <em>get_data</em> <br> <input type="radio"> <em>readr</em> <br> <input type="radio"> <em>dplyr</em> <br> <input type="radio"> <em>tidyr</em> <br></p>
<br> <details> <summary class = "btn_code"><em>Show solution</em></summary>
<p>
<p><i class="fa fa-check" aria-hidden="true" style="color: green;"></i> <code>readr</code></p>
<p><em>Great job! You are Jedi worthy!</em></p>
</p>
</details>
</div>
<div class="quiz" style="margin-top: -15px;">
<p><br></p>
<p><strong>How would you load the package <code>junkfinder</code>?</strong></p>
<p><input type="radio"> <em>junkfinder()</em> <br> <input type="radio"> <em>library(“junkfinder”)</em> <br> <input type="radio"> <em>load(“junkfinder”)</em> <br> <input type="radio"> <em>package(“junkfinder”)</em> <br></p>
<br> <details> <summary class = "btn_code"><em>Show solution</em></summary>
<p>
<p><i class="fa fa-check" aria-hidden="true" style="color: green;"></i> <code>library(&quot;junkfinder&quot;)</code></p>
<p><em>Excellent! Keep the streak going.</em></p>
</p>
</details>
</div>
</div>
</div>
<div id="ggplot2" class="section level1">
<h1><span class="header-section-number">5</span> | ggplot2</h1>
<hr>
<div id="plot-the-data-plot-the-data-plot-the-data" class="section level4 unnumbered">
<h4><em>Plot the data, Plot the data, Plot the data</em></h4>
<div class="figure">
<img src="https://images.duckduckgo.com/iu/?u=https%3A%2F%2Fd21ii91i3y6o6h.cloudfront.net%2Fgallery_images%2Ffrom_proof%2F9296%2Fmedium%2F1447173871%2Frstudio-hex-ggplot2-dot-psd.png&amp;f=1" style="float: left; margin-right: 26px; margin-top: 10px;  margin-left: 0;" width="164" />

</div>
<p><br></p>
<p>In data analysis it is really important to look at your data early and often. For that, let’s add a new package called <strong>ggplot2</strong>! <br><br></p>
<p>Install it using: <code>install.packages(&quot;ggplot2&quot;)</code></p>
<p><br><br><br></p>
<p><strong>NOTE:</strong> You can also install packages from the <code>Packages</code> tab on the lower right window of RStudio.</p>
</div>
<div id="a-first-plot" class="section level2 unnumbered">
<h2>A first plot</h2>
<p>Here’s a quick chart of how many of each item we have in the dataset.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)

<span class="kw">ggplot</span>(scrap, <span class="kw">aes</span>(<span class="dt">x =</span> Origin, <span class="dt">y =</span> Amount)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_col</span>()</code></pre></div>
<p><img src="01-Day1_junk_data_files/figure-html/unnamed-chunk-14-1.png" width="1152" /></p>
<p>Hmmm… Looks like there is an <em>All</em> category that we should look into more.</p>
</div>
<div id="introductions-first-things-first" class="section level2 unnumbered">
<h2>Introductions <em>(first things first)</em></h2>
<hr>
<p>Let’s introduce ourselves and the data we love.</p>
<p><br></p>
<div class="figure">
<img src="images/robot_1.jpg" align="left" style="margin-right:34px;" width="272" />

</div>
<blockquote>
<p><strong>Possible topics:</strong></p>
<ul>
<li>Your name<br />
</li>
<li>Your fave Star Wars character</li>
<li>Type of data you have</li>
<li>Messiest/weirdest/funniest part of your data? Or something you have to do over and over again? <strong>Hint!</strong> <em>This is something we can automate on the third day.</em></li>
</ul>
</blockquote>
</div>
<div id="key-terms" class="section level2 unnumbered">
<h2>Key terms</h2>
<hr>
<p><code>package</code> — An add-on for R that contains new functions that someone created to help you. It’s like an App for R.<br />
<code>library</code> — The name of the folder that stores all your packages, and the function used to load a package.</p>
</div>
</div>
<div id="data-exploration" class="section level1 unnumbered">
<h1>Data exploration</h1>
</div>
<div id="dplyr" class="section level1">
<h1><span class="header-section-number">6</span> | <strong>dplyr</strong></h1>
<hr>
<div class="figure">
<img src="https://d33wubrfki0l68.cloudfront.net/071952491ec4a6a532a3f70ecfa2507af4d341f9/c167c/images/hex-dplyr.png" align="left" style="margin-right: 20px; margin-top: 8px" width="120" />

</div>
<p><br></p>
<p><em>You’ve unlocked a new package!</em></p>
<p>The <em>dplyr</em> package is the go-to tool for exploring, re-arranging, and summarizing data.</p>
<p><br><br></p>
<p>Use <code>install.packages(&quot;dplyr&quot;)</code> to add <em>dplyr</em> to your library.</p>
<p><br></p>
<p><strong>Your new analysis toolbox</strong><br />
The key <em>dplyr</em> functions</p>
<table>
<thead>
<tr class="header">
<th align="left">Function</th>
<th align="left">Job</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><code>select()</code></td>
<td align="left">Select individual columns to drop, keep, or reorder</td>
</tr>
<tr class="even">
<td align="left"><code>arrange()</code></td>
<td align="left">Reorder or sort rows by value of a column</td>
</tr>
<tr class="odd">
<td align="left"><code>filter()</code></td>
<td align="left">Pick a subset of rows by the value of a column</td>
</tr>
<tr class="even">
<td align="left"><code>mutate()</code></td>
<td align="left">Add new columns or update existing columns</td>
</tr>
<tr class="odd">
<td align="left"><code>group_by()</code></td>
<td align="left">Split data into groups by values in a column</td>
</tr>
<tr class="even">
<td align="left"><code>summarize()</code></td>
<td align="left">Calculate a single summary row for the entire table</td>
</tr>
</tbody>
</table>
</div>
<div id="select" class="section level1">
<h1><span class="header-section-number">7</span> | <code>select()</code></h1>
<hr>
<p>Use the <code>select()</code> function to drop a column you no longer need, to select a few columns to create a new sub-table, or rearrange the order of your table’s columns.</p>
<div id="drop-a-single-column-with-a-minus-sign--column_name" class="section level2 unnumbered">
<h2>Drop a single column with a minus sign: <code>-column_name</code></h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;dplyr&quot;</span>)

<span class="co"># Drop the destination column</span>
<span class="kw">select</span>(scrap, <span class="op">-</span>Dest)</code></pre></div>
<pre><code>## # A tibble: 222 x 5
##    Salvage                          Origin     Amount Units Price_per_Ton
##    &lt;chr&gt;                            &lt;chr&gt;       &lt;int&gt; &lt;chr&gt;         &lt;dbl&gt;
##  1 Flight recorder                  Outskirts     887 Tons           591.
##  2 Proximity sensor                 Outskirts    7081 Tons          1229.
##  3 Vitus-Series Attitude Thrusters  Reestki      4901 Tons           226.
##  4 Aural sensor                     Tuanul        707 Tons           145.
##  5 Electromagnetic discharge filter Tuanul        107 Tons           188.
##  6 Proximity sensor                 Tuanul      32109 Tons          1229.
##  7 Hyperdrive motivator             Tuanul        862 Tons          1485.
##  8 Landing jet                      Reestki     13944 Tons          1497.
##  9 Electromagnetic discharge filter Cratertown   7788 Tons           188.
## 10 Sublight engine                  Outskirts   10642 Tons          7211.
## # ... with 212 more rows</code></pre>
</div>
<div id="drop-multiple-columns-with--ccol_1-col_2-or--col1--col2" class="section level2 unnumbered">
<h2>Drop multiple columns with <code>-c(col_1, col_2)</code> or <code>-col1, -col2</code></h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Drop the destination and units columns</span>
<span class="kw">select</span>(scrap, <span class="op">-</span><span class="kw">c</span>(Dest, Units))</code></pre></div>
<pre><code>## # A tibble: 222 x 4
##    Salvage                          Origin     Amount Price_per_Ton
##    &lt;chr&gt;                            &lt;chr&gt;       &lt;int&gt;         &lt;dbl&gt;
##  1 Flight recorder                  Outskirts     887          591.
##  2 Proximity sensor                 Outskirts    7081         1229.
##  3 Vitus-Series Attitude Thrusters  Reestki      4901          226.
##  4 Aural sensor                     Tuanul        707          145.
##  5 Electromagnetic discharge filter Tuanul        107          188.
##  6 Proximity sensor                 Tuanul      32109         1229.
##  7 Hyperdrive motivator             Tuanul        862         1485.
##  8 Landing jet                      Reestki     13944         1497.
##  9 Electromagnetic discharge filter Cratertown   7788          188.
## 10 Sublight engine                  Outskirts   10642         7211.
## # ... with 212 more rows</code></pre>
</div>
<div id="keep-only-three-columns" class="section level2 unnumbered">
<h2>Keep only three columns</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Keep the Salvage, Amount and Price_per_Ton columns</span>
<span class="kw">select</span>(scrap, <span class="kw">c</span>(Salvage, Amount, Price_per_Ton))</code></pre></div>
<pre><code>## # A tibble: 222 x 3
##    Salvage                          Amount Price_per_Ton
##    &lt;chr&gt;                             &lt;int&gt;         &lt;dbl&gt;
##  1 Flight recorder                     887          591.
##  2 Proximity sensor                   7081         1229.
##  3 Vitus-Series Attitude Thrusters    4901          226.
##  4 Aural sensor                        707          145.
##  5 Electromagnetic discharge filter    107          188.
##  6 Proximity sensor                  32109         1229.
##  7 Hyperdrive motivator                862         1485.
##  8 Landing jet                       13944         1497.
##  9 Electromagnetic discharge filter   7788          188.
## 10 Sublight engine                   10642         7211.
## # ... with 212 more rows</code></pre>
</div>
<div id="everything" class="section level2 unnumbered">
<h2><code>everything()</code></h2>
<p><code>select()</code> also works to change the order of columns. The code below moves the <code>Units</code> and <code>Amount</code> columns directly after <code>Salvage</code>, and then keeps <code>evertyhing()</code> else the same.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Make the `Salvage`, `Units`, and `Amount` columns the first three columns</span>
<span class="co"># Leave `everything()` else in the same order</span>
<span class="kw">select</span>(scrap, Salvage, Units, Amount, <span class="kw">everything</span>())</code></pre></div>
<pre><code>## # A tibble: 222 x 6
##    Salvage                  Units Amount Origin   Dest       Price_per_Ton
##    &lt;chr&gt;                    &lt;chr&gt;  &lt;int&gt; &lt;chr&gt;    &lt;chr&gt;              &lt;dbl&gt;
##  1 Flight recorder          Tons     887 Outskir~ Niima Out~          591.
##  2 Proximity sensor         Tons    7081 Outskir~ Raiders            1229.
##  3 Vitus-Series Attitude T~ Tons    4901 Reestki  Raiders             226.
##  4 Aural sensor             Tons     707 Tuanul   Raiders             145.
##  5 Electromagnetic dischar~ Tons     107 Tuanul   Niima Out~          188.
##  6 Proximity sensor         Tons   32109 Tuanul   Trade car~         1229.
##  7 Hyperdrive motivator     Tons     862 Tuanul   Trade car~         1485.
##  8 Landing jet              Tons   13944 Reestki  Niima Out~         1497.
##  9 Electromagnetic dischar~ Tons    7788 Cratert~ Raiders             188.
## 10 Sublight engine          Tons   10642 Outskir~ Niima Out~         7211.
## # ... with 212 more rows</code></pre>
</div>
</div>
<div id="arrange" class="section level1">
<h1><span class="header-section-number">8</span> | <code>arrange()</code></h1>
<hr>
<p>That’s helpful, but Rey wants to know what the highest priced Salvage items are. Use <code>arrange()</code> to find the origin city with the most highest priced Salvage item.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># find the least expensive Salvage items</span>
scrap &lt;-<span class="st"> </span><span class="kw">arrange</span>(scrap, Price_per_Ton)

<span class="co"># View the top 6 rows using head()</span>
<span class="kw">head</span>(scrap)</code></pre></div>
<pre><code>## # A tibble: 6 x 6
##   Salvage      Origin        Dest          Amount Units Price_per_Ton
##   &lt;chr&gt;        &lt;chr&gt;         &lt;chr&gt;          &lt;int&gt; &lt;chr&gt;         &lt;dbl&gt;
## 1 Aural sensor Tuanul        Raiders          707 Tons           145.
## 2 Aural sensor Outskirts     Niima Outpost   3005 Tons           145.
## 3 Aural sensor Tuanul        Raiders         6204 Tons           145.
## 4 Aural sensor Tuanul        Raiders         3120 Tons           145.
## 5 Aural sensor Blowback Town Niima Outpost   2312 Tons           145.
## 6 Aural sensor Outskirts     Trade caravan   6272 Tons           145.</code></pre>
<p><br></p>
<blockquote>
<p><strong>Well darn, that’s not a very impressive price.</strong></p>
</blockquote>
<div id="big-things-first-desc" class="section level2 unnumbered">
<h2>Big things first: <code>desc()</code></h2>
<p>To arrange a column in descending order we use: <code>desc(Price_per_Ton)</code></p>
<p><br></p>
<details> <summary class = "btn_code"> <em>Show code</em> </summary>
<p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Put most expensive items on top</span>
scrap &lt;-<span class="st"> </span><span class="kw">arrange</span>(scrap, <span class="kw">desc</span>(Price_per_Ton))

<span class="co"># View the top 6 rows</span>
<span class="kw">head</span>(scrap)</code></pre></div>
<pre><code>## # A tibble: 6 x 6
##   Salvage         Origin     Dest           Amount Units Price_per_Ton
##   &lt;chr&gt;           &lt;chr&gt;      &lt;chr&gt;           &lt;int&gt; &lt;chr&gt;         &lt;dbl&gt;
## 1 Total           All        All           2971601 Tons        579215.
## 2 Sublight engine Outskirts  Niima Outpost   10642 Tons          7211.
## 3 Sublight engine Outskirts  Raiders          2377 Tons          7211.
## 4 Sublight engine Cratertown Raiders          6310 Tons          7211.
## 5 Sublight engine Tuanul     Trade caravan    3984 Tons          7211.
## 6 Sublight engine Cratertown Raiders           299 Tons          7211.</code></pre>
</p>
<p></details></p>
<p><br></p>
<div id="exercise-2" class="section level3 unnumbered">
<h3><i class="fa fa-bicycle" aria-hidden="true" style="color: green"></i> Exercise</h3>
<p>Try arranging by more than one column (such as <code>Price</code> and <code>Amount</code>), what happens?</p>
<p><br></p>
</div>
<div id="pro-tip-2" class="section level3 unnumbered">
<h3><i class="fas fa-user-astronaut" aria-hidden="true" style="color:#040707;"></i> Pro-tip!</h3>
<blockquote>
<p>When you save an arranged data table it maintains its order. This is perfect for sending people a quick <strong>Top 10</strong> list of pollutants or sites.</p>
</blockquote>
<p><br><br></p>
<div class="figure">
<img src="images/boba_tea.jpg" width="300" />

</div>
</div>
</div>
</div>
<div id="filter" class="section level1">
<h1><span class="header-section-number">9</span> | <code>filter()</code></h1>
<hr>
<p>The <code>filter()</code> function creates a subset of the data based on the value of one or more columns. Use <code>filter()</code> to answer the questions below.</p>
<p><br></p>
<p>Do you remember we had that “All” category in the Star Wars scrap data? Let’s take a look at those records.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(scrap, Origin <span class="op">==</span><span class="st"> &quot;All&quot;</span>)</code></pre></div>
<div id="pro-tip-3" class="section level3 unnumbered">
<h3><i class="fas fa-user-astronaut" aria-hidden="true" style="color:#040707;"></i> Pro-tip!</h3>
<blockquote>
<p>We use a <code>==</code> (double equals sign) for comparing values. A <code>==</code> makes the comparison “is it equal to?” and returns a True or False answer. So the code above returns all the rows where the condition <code>Origin == &quot;All&quot;</code> is TRUE.</p>
<p>A single equals sign (<code>=</code>) is used within functions to set options, for example <code>read_csv(file = &quot;starwars_scrap_jakku.csv&quot;)</code>. Don’t worry too much. If you use the wrong symbol R is often helpful and will let you know which one is needed.</p>
</blockquote>
</div>
<div id="comparisons" class="section level2">
<h2><span class="header-section-number">9.1</span> Comparisons</h2>
<hr>
<p>To use filtering effectively you will want to know how to select observations using various comparison operators.</p>
<p><em>Key comparison operators</em></p>
<table>
<thead>
<tr class="header">
<th align="left">Symbol</th>
<th align="left">Comparison</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><code>&gt;</code></td>
<td align="left">greater than</td>
</tr>
<tr class="even">
<td align="left"><code>&gt;=</code></td>
<td align="left">greater than or equal to</td>
</tr>
<tr class="odd">
<td align="left"><code>&lt;</code></td>
<td align="left">less than</td>
</tr>
<tr class="even">
<td align="left"><code>&lt;=</code></td>
<td align="left">less than or equal to</td>
</tr>
<tr class="odd">
<td align="left"><code>==</code></td>
<td align="left">equal to</td>
</tr>
<tr class="even">
<td align="left"><code>!=</code></td>
<td align="left">not equal to</td>
</tr>
<tr class="odd">
<td align="left"><code>%in%</code></td>
<td align="left">value is in a list</td>
</tr>
<tr class="even">
<td align="left"><code>between</code></td>
<td align="left">value within a range</td>
</tr>
</tbody>
</table>
<p><br></p>
<p>Now let’s look at that data again WITHOUT the <em>All</em> category. Then we will more easily be able to see the amounts. Look in the table above and find the <code>NOT</code> operator.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">scrap &lt;-<span class="st"> </span><span class="kw">filter</span>(scrap, Origin <span class="op">!=</span><span class="st"> &quot;All&quot;</span>)</code></pre></div>
<p><br></p>
<p>Now we’ll arrange the data in descending order by <code>Amount</code> and then look at the data using the <code>head()</code> function to confirm that the “All” category is gone.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">scrap &lt;-<span class="st"> </span><span class="kw">arrange</span>(scrap, <span class="kw">desc</span>(Amount))

<span class="kw">head</span>(scrap)</code></pre></div>
<pre><code>## # A tibble: 6 x 6
##   Salvage                    Origin     Dest    Amount Units Price_per_Ton
##   &lt;chr&gt;                      &lt;chr&gt;      &lt;chr&gt;    &lt;int&gt; &lt;chr&gt;         &lt;dbl&gt;
## 1 Proximity sensor           Tuanul     Trade ~  32109 Tons          1229.
## 2 Dedicated energy receptor  Cratertown Trade ~  26167 Tons           281.
## 3 Proximity sensor           Reestki    Trade ~  22294 Tons          1229.
## 4 Reactant agitator injector Reestki    Raiders  20834 Tons           791.
## 5 Lateral thruster           Outskirts  Niima ~  20739 Tons          1571.
## 6 Sublight drive             Cratertown Niima ~  20652 Tons           420.</code></pre>
<p><br></p>
<p>Now let’s take another look at that bar chart. Is there anything else that is less than perfect with our data?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(scrap, <span class="kw">aes</span>(<span class="dt">x =</span> Origin, <span class="dt">y =</span> Amount)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_col</span>()</code></pre></div>
<p><img src="01-Day1_junk_data_files/figure-html/ggplot%20no%20All-1.png" width="672" /></p>
<p>Something still might be hidden in the data that is unexpected. Take a look at the amount of items and chart them by the units field.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(scrap, <span class="kw">aes</span>(<span class="dt">x =</span> Units, <span class="dt">y =</span> Amount)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_col</span>()</code></pre></div>
<p><img src="01-Day1_junk_data_files/figure-html/ggplot%20Units-1.png" width="672" /></p>
<p>There is still an issue with the data. The item “tons” is written two ways. This happens when multiple field technicians collect data! We will deal with this a bit later. First, what happens if we want to filter for multiple fields and categories?</p>
</div>
<div id="multiple-filters" class="section level2">
<h2><span class="header-section-number">9.2</span> Multiple filters</h2>
<hr>
<div id="exercise-3" class="section level3 unnumbered">
<h3><i class="fa fa-bicycle" aria-hidden="true" style="color: green"></i> Exercise</h3>
<p>Create a new data frame that only includes <code>Retrorockets</code> and <code>Sublight drives</code> that are priced higher than 500 credits. Give it a detailed name, something like <code>highend_starship_junk</code>.</p>
<p><em>Work with your neighbor to create the table.</em></p>
<details> <summary class = "btn_code_green"> <em>Show hint</em> </summary>
<p>
<p><strong>HINT:</strong> You will need to use the <code>c(...)</code> function and the <code>%in%</code> operator.</p>
<br>
</p>
<p></details></p>
<details> <summary class = "btn_code"> <em>Show code</em> </summary>
<p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">highend_starship_junk &lt;-<span class="st"> </span><span class="kw">filter</span>(scrap, 
                                Salvage <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Retrorocket&quot;</span>, <span class="st">&quot;Sublight drive&quot;</span>), 
                                Price_per_Ton <span class="op">&gt;</span><span class="st"> </span><span class="dv">500</span>)</code></pre></div>
<p><br></p>
</p>
<p></details></p>
<div class="quiz">
<h3 id="pop-quiz-hotshot-1" class="unnumbered">Pop Quiz, hotshot!</h3>
<p><strong>Are there more total <code>Retrorockets</code> or <code>Sublight drives</code> over 500 credits?</strong></p>
<p><input type="radio"> <em>more Retrorockets</em> <br> <input type="radio"> <em>more Sublight drives</em> <br> <input type="radio"> <em>same amount in both groups</em> <br></p>
<p><br></p>
<details> <summary class = "btn_code"> <em>Show solution</em> </summary>
<p>
<p><i class="fa fa-check" aria-hidden="true" style="color: green;"></i> <code>more Retrockets</code></p>
<p><em>There is a new light saber in your future! Great job!</em></p>
</p>
</details>
</div>
<p><br></p>
</div>
</div>
</div>
<div id="the-scrap-challenge" class="section level1 unnumbered">
<h1>The scrap challenge <i class="fa fa-rocket" aria-hidden="true"></i></h1>
<hr>
<blockquote>
<p>Ask your neighbor a question about the scrap data that requires filter and the <strong>%in%</strong> operator. Try to answer your neighbor’s question.</p>
</blockquote>
<p><br></p>
<p><strong>HINT:</strong> Ask about the <strong>Most</strong> or <strong>Least</strong> of something</p>
<p><br><br></p>
<details> <summary class = "btn_code_blue"> <strong>EXPLORE:</strong> <em>What is the <strong>c()</strong> thing again?</em> </summary>
<p>
<p>You can put multiple values inside <code>c()</code> to make a vector of items. Each item in the vector is separated by a comma. Let’s create a short vector of our favorite colors.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># This is an example vector</span>
fave_colors &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;green&quot;</span>, <span class="st">&quot;orange&quot;</span>, <span class="st">&quot;cornflower&quot;</span>)

fave_colors</code></pre></div>
<pre><code>## [1] &quot;green&quot;      &quot;orange&quot;     &quot;cornflower&quot;</code></pre>
<br>
</p>
<p></details></p>
</div>
<div id="update-from-bb8" class="section level1">
<h1><span class="header-section-number">10</span> | Update from BB8!</h1>
<hr>
<div class="figure">
<img src="images/rey_bb8.jpg" align="right" style="margin-top: 0px; margin-left: 15px; margin-right: 0px;" width="270" />

</div>
<div id="rey-needs-our-help." class="section level4 unnumbered">
<h4>Rey needs our help.</h4>
<p><em>Let’s help Rey!</em></p>
<p>Rey’s droid was able to recover the full scrap data from the notorious Junk Boss Unkar Plutt. Check your folder for the new dataset named: <code>starwars_scrap_jakku_full.csv</code>.</p>
<p>You know Rey needs parts for her star ship. And you are especially interested in influencing Rey to trade with scrappers from your home City on Jakku.</p>
<p><br></p>
<p><strong>Look under your keyboard to find the name of your City in Jakku.</strong></p>
<p><br></p>
</div>
<div id="more-scrap" class="section level3 unnumbered">
<h3>More scrap</h3>
<p>First, let’s read in the full dataset.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;readr&quot;</span>)

file_path &lt;-<span class="st"> &quot;data/starwars_scrap_jakku_full.csv&quot;</span>

scrap &lt;-<span class="st"> </span><span class="kw">read_csv</span>(file_path)</code></pre></div>
<p><br></p>
<p>It looks like there are additional units of salvage items beyond “tons”. We may have some data cleaning to do.</p>
</div>
</div>
<div id="glimpse" class="section level1">
<h1><span class="header-section-number">11</span> | <code>glimpse()</code></h1>
<hr>
<p>Take a minute to look at the full scrap transfer data. An R function called <em>glimpse()</em> is a good place to start.</p>
<p><br></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">glimpse</span>(scrap)</code></pre></div>
<pre><code>## Observations: 221
## Variables: 6
## $ Salvage       &lt;chr&gt; &quot;Proximity sensor&quot;, &quot;Dedicated energy receptor&quot;,...
## $ Origin        &lt;chr&gt; &quot;Tuanul&quot;, &quot;Cratertown&quot;, &quot;Reestki&quot;, &quot;Reestki&quot;, &quot;O...
## $ Dest          &lt;chr&gt; &quot;Trade caravan&quot;, &quot;Trade caravan&quot;, &quot;Trade caravan...
## $ Amount        &lt;int&gt; 32109, 26167, 22294, 20834, 20739, 20652, 18423,...
## $ Units         &lt;chr&gt; &quot;Tons&quot;, &quot;Tons&quot;, &quot;Tons&quot;, &quot;Tons&quot;, &quot;Tons&quot;, &quot;Tons&quot;, ...
## $ Price_per_Ton &lt;dbl&gt; 1229.03, 281.01, 1229.03, 790.68, 1570.65, 420.3...</code></pre>
<p><br></p>
<p>You can see that the units in the full data set are in “Items”, “Cubic Yards”. And you remember from before that there were also units of “TONS” and “Tons”.</p>
<p><br></p>
<div id="exercise-4" class="section level3 unnumbered">
<h3><i class="fa fa-bicycle" aria-hidden="true" style="color: green"></i> Exercise</h3>
<p>Use <code>filter()</code> and <code>arrange()</code> to get a new data frame of your City’s scrap sorted by <code>Price_per_Ton</code>. Then take a look at the first couple of rows in your table to find the Salvage that fetches the highest prices.</p>
<details> <summary class = "btn_code_green"> <em>Show hint</em> </summary>
<p>
<p><strong>Hint:</strong> First filter your data to include only your City in the <code>Origin</code> column.</p>
<br>
</p>
<p></details></p>
<details> <summary class = "btn_code"> <em>Show code</em> </summary>
<p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">my_city_scrap &lt;-<span class="st"> </span><span class="kw">filter</span>(scrap, Origin <span class="op">==</span><span class="st"> &quot;...&quot;</span>)

my_scrap &lt;-<span class="st"> </span><span class="kw">arrange</span>(my_city_scrap, <span class="kw">desc</span>(Price_per_Ton))</code></pre></div>
<br>
</p>
<p></details></p>
</div>
<div id="great-work" class="section level2 unnumbered">
<h2>Great work!</h2>
<hr>
<p>You’ve earned a Star Wars film fan award! Hopefully you found a way to help Rey and your home City.</p>
<p><br></p>
<details> <summary>
<button class="btn_code">
<strong>Receive your badge</strong>
</button>
</summary>
<p>
<p><img src="https://upload.wikimedia.org/wikipedia/en/6/6d/SWFFA.jpg" width="200" style="margin-top: 10px; margin-right: 30px;"></p>
<p><br></p>
</p>
<p></details></p>
<p><br></p>
<div id="recap" class="section level3 unnumbered">
<h3><i class="fa fa-hourglass-half" aria-hidden="true" style="color:#040707;"></i> <strong>RECAP</strong></h3>
<blockquote>
<ul>
<li><p>What packages have we added to our <code>library</code>?</p></li>
<li><p>What new functions have we learned?</p></li>
</ul>
</blockquote>
</div>
</div>
</div>
<div id="shutdown-complete" class="section level1">
<h1><span class="header-section-number">12</span> | Shutdown complete</h1>
<p>When you close RStudio it will ask you about saving your <em>workspace</em> and other files. This can get tiresome after awhile. Follow the steps below to set these options once and for always.</p>
<p>Turn off <strong>“Save Workspace”</strong></p>
<ul>
<li>Go to <strong>Tools</strong> on the top RStudio navigation bar.</li>
<li>Choose <code>Global Options...</code>.</li>
<li>On the first screen:</li>
<li>Set <em>Save workspace to .RData on exit:</em> to “Never”.</li>
<li>Uncheck <em>Always save history</em></li>
<li>Uncheck <em>Restore .Rdata into workspace at startup</em></li>
</ul>
<div id="survey-says" class="section level2 unnumbered">
<h2>Survey says</h2>
<hr>
<p>On the <strong>front</strong> of your sticky note answer one of these:</p>
<ul>
<li>Something you really liked learning today?</li>
<li>A useful thing you learned?</li>
<li>A new skill you are you excited about using?</li>
</ul>
<p>On the <strong>back</strong>:</p>
<ul>
<li>A lingering question you have about the material.</li>
<li>A topic that was confusing and could use more clarification?</li>
</ul>
<p>We will compile the questions and send out answers before next class. If you think of something later, please e-mail us any questions you have. If you’re uncertain about something I guarantee someone else is as well. So help a friend, and ask a question.</p>
</div>
<div id="congratulations-youve-completed-day-1." class="section level2 unnumbered">
<h2>Congratulations! You’ve completed <strong>Day 1</strong>.</h2>
<hr>
<div class="figure">
<img src="https://media1.tenor.com/images/ce269fabe989f148f84d339850ce9a8f/tenor.gif?itemid=3561486" />

</div>
<p><br></p>
</div>
</div>
<div id="return-to-homebase" class="section level1 unnumbered">
<h1><i class="fa fa-rocket" aria-hidden="true"></i> Return to <a href="index.html">Homebase</a></h1>
<p><br></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
